# Generated by Django 6.0.6 on 2026-06-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('tag', models.CharField(blank=True, max_length=100, verbose_name='الوسم')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='الصورة')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'الشريحة الرئيسية',
                'verbose_name_plural': 'الشرائح الرئيسية',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('icon_name', models.CharField(max_length=50, verbose_name='اسم الأيقونة')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='التسمية')),
                ('value', models.PositiveIntegerField(verbose_name='القيمة')),
                ('description', models.CharField(max_length=200, verbose_name='الوصف')),
                ('icon_name', models.CharField(max_length=50, verbose_name='اسم الأيقونة')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'إحصائية الموقع',
                'verbose_name_plural': 'إحصائيات الموقع',
                'ordering': ['order'],
            },
        ),
    ]
