# Generated by Django 6.0.6 on 2026-06-18 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('blog', 'مقال'), ('story', 'قصة نجاح')], max_length=10, verbose_name='النوع')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('brief', models.TextField(blank=True, verbose_name='مقدمة قصيرة')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='صورة الغلاف')),
                ('reading_minutes', models.PositiveSmallIntegerField(default=3, verbose_name='وقت القراءة (دقائق)')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ النشر')),
            ],
            options={
                'verbose_name': 'مقال / قصة',
                'verbose_name_plural': 'المقالات والقصص',
                'ordering': ['-created_at'],
            },
        ),
    ]
