# Generated by Django 6.0.6 on 2026-06-20 09:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0003_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='الاسم')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('message', models.TextField(blank=True, verbose_name='الرسالة')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='مجهول الهوية')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التبرع')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camp.article', verbose_name='قصة مرتبطة')),
            ],
            options={
                'verbose_name': 'تبرع',
                'verbose_name_plural': 'التبرعات',
                'ordering': ['-created_at'],
            },
        ),
    ]
